import Head from 'next/head'
import { Inter } from '@next/font/google'
import PopularitySelect from '../components/PopularitySelect'
import SearchInput from '../components/SearchInput'
import ViewsButton from '../components/ViewsButton'
import { LinearDemo } from '../components/svg'
import { GridDemo } from '../components/svg'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Beauty App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main >
        beauty Shop
        <PopularitySelect />
        <SearchInput />
        <ViewsButton viewsIcon={<LinearDemo />} />
        <ViewsButton viewsIcon={<GridDemo />} />
      </main>
    </>
  )
}
